### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by HashRocketSyntax** [emehrkay/Pypher#16]
Am I correct in saying that pypher is looking for your models in it's arguments?

Can it be configured to access a Neo4j database directly, or does it rely on something like neomodel to setup the models?

**Comment by emehrkay** [comment]
Pypher is just a query(Cypher) builder. It doesn't do any connections or data modeling, you'd need another library for this. Pypher _could_ be used with existing libraries, it may take some extra work to make that a possibility though (I am working on an OGM based on Pypher, I will ping you when there is something to show).

Pypher's goal is to simply give you an object to manipulate and create a Cypher string instead of concatenating strings together in Python.

**Comment by HashRocketSyntax** [comment]
okay so main takeaway is that it assembles strings and let's you pass in your python variables
