### ISSUE TITLE
function in rhs of attribute setting?

### ISSUE THREAD

**Issue by ianedwardthomas** [emehrkay/Pypher#26]
I am trying to create the Pypher equivalent of the cypher:

MERGE (p:person { lastname: coalesce(var, 'unknown last name')}) ...

where var could be some last name, including null, substituted in at run time in python.

The problem is the coalesce function on the rhs of the attribute.

without the coalesce function 
lastname=Param('lastname, var) 
works, but how do I add the neo4j function in there.  I tried 

lastname= Param('lastname', __coalesce(var, 'unknown last name'))
but this gives a Pypher object in the bound parameters which doesn't seem right.

Any ideas anyone.

**Comment by emehrkay** [comment]
This is a good catch. It seems that parameter binding does not support nested Pypher instances. Give me a minute to think this through, I will have a solution for you

**Comment by emehrkay** [comment]
Okay, this should be fixed in the latest version (0.16.0). 

Check out these two new test cases, complete with your example, on the two ways that you can use it: https://github.com/emehrkay/Pypher/blob/master/pypher/test/builder.py#L1368

via tester:
![screen shot 2019-02-11 at 9 11 39 pm](https://user-images.githubusercontent.com/24242/52606742-ab1bf980-2e41-11e9-9a54-eb5ff0c95d51.png)

**Comment by ianedwardthomas** [comment]
Looks good and working well with my example.  Thanks for the help!
